language: minimal
dist: xenial # TODO: replace to bionic when fix https://github.com/travis-ci/travis-ci/issues/9460

git:
  depth: 50
  submodules: true

before_cache:
  - sudo service docker stop
  - sudo chown -R travis ~/docker

env:
  global:
    - DOCKER_DIR="$HOME/docker"
    - APT_CACHE_DIR="$HOME/apt-cache"

cache:
  directories:
    - $DOCKER_DIR
    - $APT_CACHE_DIR

notifications:
  email: false

before_install:
  - pwd

  # Load apt cache
  - |
    for i in $APT_CACHE_DIR/*.deb; do
      if [ -f "$i" ]; then sudo cp -p $APT_CACHE_DIR/*.deb /var/cache/apt/archives/; break; fi
    done

  # Update system
  - sudo apt-get -q -y -o Dpkg::Use-Pty=0 update
    
  # Remove unnecessary packages
  - sudo apt-get -q -y -o Dpkg::Use-Pty=0 purge openjdk-* icedtea* postgresql-*  mysql-*

  # Remove old docker
  - sudo service docker stop
  - sudo apt-get -q -y -o Dpkg::Use-Pty=0 remove docker docker-engine docker.io containerd runc

  # Upgrade system
  - sudo apt-get -q -y -o Dpkg::Use-Pty=0 autoremove
  - sudo LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -q -y -o Dpkg::Use-Pty=0 upgrade
  - sudo apt-get -q -y -o Dpkg::Use-Pty=0 autoremove

  # Install docker (read more: https://docs.docker.com/install/linux/docker-ce/ubuntu/ )
  - sudo apt-get -q -y -o Dpkg::Use-Pty=0 install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -q -y -o Dpkg::Use-Pty=0 update
  - sudo apt-get -q -y -o Dpkg::Use-Pty=0 install docker-ce docker-ce-cli containerd.io
  - docker -v

  # Update docker images from cache
  - sudo service docker stop
  - if [ "$(ls -A /home/travis/docker)" ]; then echo "/home/travis/docker already set"; else sudo mv /var/lib/docker $DOCKER_DIR; fi
  - sudo bash -c "echo 'DOCKER_OPTS=\"-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -g /home/travis/docker\"' > /etc/default/docker"
  - sudo service docker start

  # Install Packages for i2s
  - sudo apt-get -q -y -o Dpkg::Use-Pty=0 install go-md2man

  # Update apt cache
  - sudo apt-get autoclean -q -y
  - rm -rf $APT_CACHE_DIR/*.deb
  - cp -p /var/cache/apt/archives/*deb $APT_CACHE_DIR

install:
  # Build php 7.3 Centos 7 i2s docker image
  - make tag TARGET=centos7 VERSIONS=i2s_centos7_php73

script:
  - echo "All done"
