language: php
dist: xenial # TODO: replace to bionic when fix https://github.com/travis-ci/travis-ci/issues/9460

php:
  - 7.3
  -
env:
  - TEST=test

before_install:
  - sudo apt-get update -y
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Remove Xdebug as we don't need it and it causes
  # "PHP Fatal error: Maximum function nesting level of '256' reached".
  # We don't care if that file exists or not on PHP 7.
  - phpenv config-rm xdebug.ini || true

  # Update composer.
  - composer --verbose self-update
  - composer --version

  # install Percona Server
  #   https://www.percona.com/doc/percona-server/8.0/installation/apt_repo.html
  #   https://www.percona.com/doc/percona-server/8.0/myrocks/install.html
  # Fetch the repository packages from Percona web
  - wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
  # Install the downloaded package with dpkg. To do that, run the following commands as root or with sudo
  - sudo dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
  # Enable the repository
  - sudo percona-release setup ps80
  # Install the server package
  - sudo apt-get install percona-server-rocksdb -y
  # Starting the service
  - service mysql start
  # enable the RocksDB storage engine in Percona Server
  - sudo ps-admin --enable-rocksdb -u root -pPassw0rd

install:
  # Install Composer dependencies.
  - composer --verbose validate
  - composer --verbose install

script:
  - cd $TRAVIS_BUILD_DIR/web

#   - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
#   - ./../vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
#   - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
#   # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
#   # Ignore PageCache group temporarily, @see https://www.drupal.org/node/2770673
#   # Ignore Setup group temporarily, @see https://www.drupal.org/node/2962157
#   - ./../vendor/bin/phpunit -c core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache,Setup
#   - ./../vendor/bin/drush
#   - if [[ $RELEASE = stable ]]; then ./../vendor/bin/drupal; fi;
