language: minimal
dist: xenial # TODO: replace to bionic when fix https://github.com/travis-ci/travis-ci/issues/9460

git:
  depth: 50
  submodules: false

cache:
  directories:
    - $HOME/apt-cache

notifications:
  email: false

before_install:
  - pwd
  - export APT_CACHE_DIR="$HOME/apt-cache"

  # Loading apt cache
  - |
    for i in $APT_CACHE_DIR/*.deb; do
      if [ -f "$i" ]; then sudo cp -p $APT_CACHE_DIR/*.deb /var/cache/apt/archives/; break; fi
    done
    
  # Remove unnecessary packages
  - sudo apt-get -qq -o=Dpkg::Use-Pty=0 purge -y openjdk-* icedtea icedtea* postgresql-*  mysql-*

  # Remove docker
  - sudo service docker stop
  - sudo apt-get -qq -o=Dpkg::Use-Pty=0 remove -y docker docker-engine docker.io containerd runc

  # Update system
  - sudo LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -qq -o=Dpkg::Use-Pty=0 update -y
  - sudo apt-get -qq -o=Dpkg::Use-Pty=0 upgrade -y
  - sudo apt-get -qq -o=Dpkg::Use-Pty=0 autoremove -y
  
  # Install docker (read more: https://docs.docker.com/install/linux/docker-ce/ubuntu/ )
  - sudo apt-get -qq -o=Dpkg::Use-Pty=0 install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -qq -o=Dpkg::Use-Pty=0 update -y
  - sudo apt-get -qq -o=Dpkg::Use-Pty=0 install -y docker-ce docker-ce-cli containerd.io
  - sudo service docker status

  # TODO



  # Updating apt cache
  - sudo apt-get autoclean -q -y
  - rm -rf $APT_CACHE_DIR/*.deb
  - cp -p /var/cache/apt/archives/*deb $APT_CACHE_DIR

script:
  - echo "All done"
