#!/usr/bin/env bash

# DONT BUILD WHEN USED "set -e"

# IMPORTANT: Do not add more content to this file unless you know what you are
#            doing. This file is sourced every time the shell session is opened.
# This will make scl collection binaries work out of box.
unset BASH_ENV PROMPT_COMMAND ENV
